services:
  db:
    image: mysql:8.3.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./tearup/university/table.sql:/docker-entrypoint-initdb.d/1-table.sql
      - ./tearup/university/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - ./tearup/grant.sql:/docker-entrypoint-initdb.d/grant.sql
    ports:
      - "3306:3306"
    restart: always
